# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bfd64b8ac7e0048404c3ed15efb1582e9fbfe1dfd338da9a7a238905fc636cce226d7793d7a21f34c986e715acc1071cf6da0a7428177e06b9c40f3d5eb85cf

test:
  secret_key_base: 236c96b617cdfa03706f60374d941c25efe407178388995e781d64a1a4566e4d51f5c6428d3a71c12b5d54dc4aea636c97c02c2816be02d28b2d19d35e50271d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
